### PR TITLE
Basic In-App Support, Preloaders, and much more

### PR DESCRIPTION
**Pull request by sGerli**
- Added basic in-app support `/?platform=(ios or android)&watchPlatform=(basalt, aplite, chalk, diorite, and emery works for the apps that support it but almost no one will notice)`
- Added special footer for in-app
- Removed navbar during in-app
- Made spacing a bit more consistent for in-app
- Cleaned app-versions and app-details, and merged them under a parent `/app`
- Moved backend connections to vue-resources
- Added card loader
- Added screenshot loader
- Re-added history routing mode that was removed during the package update PR

### CODE REVIEW

**Review by azertyfun — CHANGES_REQUESTED** [review]
The in-app view (on firefox at least) has some graphical glitches: [app title](https://i.imgur.com/hF3po4F.png), [apps page grid](https://i.imgur.com/VtVfXaA.png). Otherwise this is a mighty fine job you have done here!

**Comment by sGerli** [comment]
Those two issues have always been there, I’ll look into them

**Comment by sGerli** [comment]
Already solved the title issue, but the other one is related to css columns being irregular, help is appreciated.
The grid stops working correctly at about 576px width.

**Comment by sGerli** [comment]
Card sizing issue fixed, waiting for your check @azertyfun

**Review by azertyfun — APPROVED** [review]

**Pull request merged**
