### PR TITLE
Cleaned up the SVG icons 

### PR DESCRIPTION
**Pull request by mvaneijgen**
I think there should be a difference between SVG icons and just graphics that are in the format of SVG. This way we can scope the CSS for the icon set for just the icons. The CSS `use` hack was applied on all `svg * {...}` and is not applied to `#svgContainer * {...}` which wil it play nice with our pet rock. 

What also can be a smart idea is create some sort of icons styling system so that we don't directly style the icon (eg `.icon-download { fill: red; }`), but rather let the sytling be applied via the container it is in (eg `#navbar .icon { storke: grey }`) or via a styling class (I like [BEM](http://getbem.com/introduction/)) `.icon--basecolor { fill: orange;}`

### CODE REVIEW

**Comment by KonradIT** [comment]
Cool! I think @sGerli wanted the Download icon to be in polygons and XML tags, not a 'image' string which I did, I am trying to convert the icon to polygons like the Like Button but I cannot seem to get a clear icon. The fixed icons are in 'vue' branch right?

**Comment by mvaneijgen** [comment]
@KonradIT the icons are [here](https://github.com/pebble-dev/rebble-store/tree/vue/src/assets/svg) and when issue https://github.com/pebble-dev/rebble-store/issues/56 is completed there will be a sprite of all the icons SVGs and then you can reference the icons at any location using :

```
<svg class="icon-search" width="25px" height="25px" viewBox="0 0 25 25" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
   <use xlink:href="#iconSearch"></use>
</svg>
```

**Comment by mvaneijgen** [comment]
You can do only one PR at a time? I am still really bad at Git, so I closed this PR and created a new one (https://github.com/pebble-dev/rebble-store/pull/64) with the SVG and SASS changes.

**Comment by sGerli** [comment]
@mvaneijgen yes you can only PR one at a time from a branch but you PR auto-updates for new commits before being merged.

**Pull request closed without merging**
