### PR TITLE
Add companion icon/links to AppDetails page

### PR DESCRIPTION
**Pull request by phosphotungstic**
Added companion icon/links to AppDetails page.
Added in SVGs for Apple/Android icons.

Companion icon/links only show up on app pages and not watchface pages.

### CODE REVIEW

**Comment by sGerli** [comment]
Seems to be working, I think we should remove the get app button and eventually replace it with the companion link and tell the user more explicitly that this app requires a companion app. I would put this info in an extra section below the app title bar.

**Comment by phosphotungstic** [comment]
By the get app button, do you mean the one at the top or the icons I just added?
I agree that a message to the user about needing a companion app would be useful.

**Comment by sGerli** [comment]
I would move all of that up there.
a0fa651a-4c62-49c5-a33c-2ac27c0bcaf1

**Comment by phosphotungstic** [comment]
Finished the agreed-upon changes!

**Pull request merged**
