### PR TITLE
Added GNU AGPLv3 license

### PR DESCRIPTION
**Pull request by Avamander**

### CODE REVIEW

**Comment by sGerli** [comment]
@Zetaphor @KonradIT and other contributors, what do you think about adding this license?

**Comment by KonradIT** [comment]
License is go over here.

**Comment by Zetaphor** [comment]
LGTM

**Comment by Avamander** [comment]
@mvaneijgen @magmastonealex Sorry to bother you but your agreement is needed.

**Comment by mvaneijgen** [comment]
I have no clue how licenses work, so if some one has experience with them and thinks this is the best license for this project I am fine with that.

**Comment by magmastonealex** [comment]
Yes, I agree

**Comment by Avamander** [comment]
@sGerli All contributors have agreed, you can merge the request.

**Pull request merged**
