### PR TITLE
Build svg's

### PR DESCRIPTION
**Pull request by MHC03**
This is a possible solution for #56. 
- The inline-svg's seemed to differ from the files, so I put all of them into their corresponding file.
- All svgs in assets/svg are loaded through require.context resulting in two "drawbacks".
    - `svg-container` is now empty
    - svg files are added into the DOM above the app div: 
firefox_2018-02-04_19-43-39
- Id's are set automatically through the loader.

I am again not sure, whether this is what you wanted, so I would be glad for an explanation, if I understood it wrong.

### CODE REVIEW

**Review by sGerli — COMMENTED** [review]
Yes, this is exactly what we were looking for, but if we could only load the SVGs that are going to be used in that view I think it would be better

**Comment by MHC03** [comment]
- Changed svg element in svgContainer to div
- the global svg is now directly added to the svgContainer div

**Comment by sGerli** [comment]
@MHC03 What do you think about what I said in my last comment? Is it possible?

**Comment by MHC03** [comment]
Oh sry, I just realized that you meant something else with your previous comment. So, you only want to load the svg's if they are in the current view, right? And the reason you were doing it through the svg container beforehand was because of the css styles? 
We maybe could make a global component, which we can call to load the currently needed svg. In this component we could define those needed css styles for the svgs. So the xref links would directly be provided through it. I mean to have seen this somewhere when researching to solve this problem. If it actually is what you want, I can try to implement it. If I still don't get what you mean, I would need a more detailed elaboration.

EDIT: Something like [this](http://joanmira.com/vuejs-first-impression-and-how-to-work-with-svgs/)?

**Comment by sGerli** [comment]
Yes

**Comment by MHC03** [comment]
While thinking about the solution some more questions arose for me. I hope the questioning does not get on your nerves. 

1. As the page is a Single Page Application, the `svgContainer` won't change on a new view. So the question is, should it be refreshed on every view? Wouldn't this make unnecessary loading on every view change?
1. Or should the `svgContainer` be a part of the view, so that it is loaded with the view and contains only the used svg's. 
1. Another possible solution would be to make all icons inline. But this does not sound right for me, either.

**Comment by sGerli** [comment]
Hmm you're right, for performance it's probably better to load them all at the start, so I'll merge if you think this is finished.

**Comment by MHC03** [comment]
It's finished for me if you are fine with it.

**Pull request merged**
