### PR TITLE
Move to MIT license

### PR DESCRIPTION
**Pull request by sGerli**
Hi contributors, as some of you may be aware of we originally chose a license without even knowing it's implications. Today as a petition from @Katharine we are starting this request to change this projects license to a MIT license, this with the purpose of getting more developers in that may be scared by the current license. In order to change this license we need your approval so if you've contributed code to this project please comment in here saying "I approve".

### CODE REVIEW

**Comment by sGerli** [comment]
Hi, please answer this PR as soon as possible:

- [x]  @MHC03
- [x]  @Zetaphor
- [x]  @mvaneijgen
- [x]  @KonradIT
@Allen-B1Since he didn't respond I reverted all of his changes
- [x]  @azertyfun
- [x]  @magmastonealex

**Comment by magmastonealex** [comment]
I approve.

**Comment by phpeter** [comment]
I approve.

**Comment by MHC03** [comment]
I approve.

**Review by KonradIT — APPROVED** [review]

**Comment by KonradIT** [comment]
I approve.

**Comment by Zetaphor** [comment]
I approve

**Review by Zetaphor — APPROVED** [review]

**Review by azertyfun — APPROVED** [review]
I approve.

**Comment by mvaneijgen** [comment]
I approve.

**Comment by glebm** [comment]
@Allen-B1 ping

**Pull request merged**
